// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qr_binarize_qr_binarize_Pipeline_VITIS_LOOP_21_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_TVALID,
        dst_TREADY,
        size,
        src_TDATA,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TLAST,
        threshold,
        invert,
        sub_i_i,
        dst_TDATA,
        dst_TVALID,
        dst_TKEEP,
        dst_TSTRB,
        dst_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
input   dst_TREADY;
input  [31:0] size;
input  [31:0] src_TDATA;
output   src_TREADY;
input  [3:0] src_TKEEP;
input  [3:0] src_TSTRB;
input  [0:0] src_TLAST;
input  [7:0] threshold;
input  [0:0] invert;
input  [32:0] sub_i_i;
output  [7:0] dst_TDATA;
output   dst_TVALID;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TLAST;

reg ap_idle;
reg src_TREADY;
reg dst_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln1027_fu_158_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    src_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    dst_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] g_reg_301;
reg   [7:0] g_reg_301_pp0_iter1_reg;
reg   [7:0] b_V_reg_306;
wire   [0:0] pout_last_V_fu_206_p2;
reg   [0:0] pout_last_V_reg_316;
reg   [0:0] pout_last_V_reg_316_pp0_iter1_reg;
reg   [0:0] pout_last_V_reg_316_pp0_iter2_reg;
reg   [0:0] pout_last_V_reg_316_pp0_iter3_reg;
wire   [15:0] ret_V_7_fu_223_p2;
wire   [15:0] grp_fu_263_p3;
reg   [31:0] i_V_fu_92;
wire   [31:0] i_V_2_fu_164_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_V_1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] r_fu_174_p1;
wire   [32:0] zext_ln1019_fu_202_p1;
wire   [7:0] ret_V_7_fu_223_p0;
wire   [8:0] ret_V_7_fu_223_p1;
wire   [15:0] grp_fu_271_p3;
wire   [7:0] trunc_ln_fu_229_p4;
wire   [0:0] icmp_ln1031_fu_238_p2;
wire   [0:0] white_V_fu_243_p2;
wire   [0:0] ret_V_8_fu_249_p2;
wire   [7:0] grp_fu_263_p0;
wire   [6:0] grp_fu_263_p1;
wire   [7:0] grp_fu_271_p0;
wire   [4:0] grp_fu_271_p1;
reg    grp_fu_263_ce;
reg    grp_fu_271_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_263_p00;
wire   [12:0] grp_fu_271_p00;
wire   [15:0] ret_V_7_fu_223_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

qr_binarize_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U1(
    .din0(ret_V_7_fu_223_p0),
    .din1(ret_V_7_fu_223_p1),
    .dout(ret_V_7_fu_223_p2)
);

qr_binarize_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_263_p0),
    .din1(grp_fu_263_p1),
    .din2(ret_V_7_fu_223_p2),
    .ce(grp_fu_263_ce),
    .dout(grp_fu_263_p3)
);

qr_binarize_mac_muladd_8ns_5ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_5ns_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_271_p0),
    .din1(grp_fu_271_p1),
    .din2(grp_fu_263_p3),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p3)
);

qr_binarize_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1027_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            i_V_fu_92 <= i_V_2_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_V_fu_92 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        g_reg_301_pp0_iter1_reg <= g_reg_301;
        pout_last_V_reg_316_pp0_iter1_reg <= pout_last_V_reg_316;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        pout_last_V_reg_316_pp0_iter2_reg <= pout_last_V_reg_316_pp0_iter1_reg;
        pout_last_V_reg_316_pp0_iter3_reg <= pout_last_V_reg_316_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_V_reg_306 <= {{src_TDATA[23:16]}};
        g_reg_301 <= {{src_TDATA[15:8]}};
        pout_last_V_reg_316 <= pout_last_V_fu_206_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1027_fu_158_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_V_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_V_1 = i_V_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        dst_TDATA_blk_n = dst_TREADY;
    end else begin
        dst_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        dst_TVALID = 1'b1;
    end else begin
        dst_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_263_ce = 1'b1;
    end else begin
        grp_fu_263_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_271_ce = 1'b1;
    end else begin
        grp_fu_271_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TDATA_blk_n = src_TVALID;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_fu_158_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TREADY = 1'b1;
    end else begin
        src_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((dst_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln1027_fu_158_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((dst_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln1027_fu_158_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((dst_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln1027_fu_158_p2 == 1'd0) & (src_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln1027_fu_158_p2 == 1'd0) & (src_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (dst_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dst_TDATA = ((ret_V_8_fu_249_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign dst_TKEEP = 1'd1;

assign dst_TLAST = pout_last_V_reg_316_pp0_iter3_reg;

assign dst_TSTRB = 1'd1;

assign grp_fu_263_p0 = grp_fu_263_p00;

assign grp_fu_263_p00 = r_fu_174_p1;

assign grp_fu_263_p1 = 15'd77;

assign grp_fu_271_p0 = grp_fu_271_p00;

assign grp_fu_271_p00 = b_V_reg_306;

assign grp_fu_271_p1 = 13'd29;

assign i_V_2_fu_164_p2 = (ap_sig_allocacmp_i_V_1 + 32'd1);

assign icmp_ln1027_fu_158_p2 = ((ap_sig_allocacmp_i_V_1 == size) ? 1'b1 : 1'b0);

assign icmp_ln1031_fu_238_p2 = ((trunc_ln_fu_229_p4 < threshold) ? 1'b1 : 1'b0);

assign pout_last_V_fu_206_p2 = ((sub_i_i == zext_ln1019_fu_202_p1) ? 1'b1 : 1'b0);

assign r_fu_174_p1 = src_TDATA[7:0];

assign ret_V_7_fu_223_p0 = ret_V_7_fu_223_p00;

assign ret_V_7_fu_223_p00 = g_reg_301_pp0_iter1_reg;

assign ret_V_7_fu_223_p1 = 16'd150;

assign ret_V_8_fu_249_p2 = (white_V_fu_243_p2 ^ invert);

assign trunc_ln_fu_229_p4 = {{grp_fu_271_p3[15:8]}};

assign white_V_fu_243_p2 = (icmp_ln1031_fu_238_p2 ^ 1'd1);

assign zext_ln1019_fu_202_p1 = ap_sig_allocacmp_i_V_1;

endmodule //qr_binarize_qr_binarize_Pipeline_VITIS_LOOP_21_1
