
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xqr_binarize.h"

/*
* The configuration table for devices
*/

XQr_binarize_Config XQr_binarize_ConfigTable[XPAR_XQR_BINARIZE_NUM_INSTANCES] =
{
	{
		XPAR_QR_BINARIZE_0_DEVICE_ID,
		XPAR_QR_BINARIZE_0_S_AXI_CTRL_BASEADDR
	}
};


